#pragma once
#include <iostream>
#include <memory>
#include <vector>
#include <string>
#include "ScalarField.hpp"
#include "ColorField.hpp"
#include "Camera.hpp"
#include "RayMarch.hpp"
#include "Light.hpp"
#include "Triangle.hpp"
#include "OBJ_Loader.h"